marketing_analytics_demo:
  target: dev
  outputs:
    dev:
      host: e2-demo-field-eng.cloud.databricks.com
      http_path: "/sql/1.0/endpoints/679731b724da90f6"
      catalog: users
      schema: tahir_fayyaz
      threads: 8
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
      type: databricks
