marketing_analytics_demo:
  target: dev
  outputs:
    dev:
      host: "{{ env_var('DBT_HOST') }}"
      http_path: "sql/protocolv1/o/{{ env_var('DBT_ORG_ID') }}/{{ env_var('DBT_CLUSTER_ID') }}"
      catalog: users
      schema: tahir_fayyaz
      threads: 8
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
      type: databricks
